"""empty message

Revision ID: 47179b649b7a
Revises: 0f8fcfe9f838
Create Date: 2025-05-04 18:04:15.898980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47179b649b7a'
down_revision = '0f8fcfe9f838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('pw_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
