"""Reset and create tables with user profile fields

Revision ID: 83896f702866
Revises: 47179b649b7a
Create Date: 2025-05-07 15:10:13.327953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83896f702866'
down_revision = '47179b649b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('pw_hash', sa.String(length=128), nullable=False),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('occupation', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
