"""empty message

Revision ID: 8845e9687622
Revises: f49c060cc33f
Create Date: 2025-05-16 09:50:11.805927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8845e9687622'
down_revision = 'f49c060cc33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thought',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('emotions', sa.Text(), nullable=True),
    sa.Column('space', sa.String(length=10), nullable=True),
    sa.Column('author', sa.String(length=80), nullable=True),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('local_position', sa.JSON(), nullable=True),
    sa.Column('tombstone', sa.Integer(), nullable=True),
    sa.Column('likes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('pw_hash', sa.String(length=128), nullable=False),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('occupation', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('thought')
    # ### end Alembic commands ###
