"""empty message

Revision ID: 9eef7d89f749
Revises: 4ec1d1bb1742
Create Date: 2025-05-10 10:50:26.868897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eef7d89f749'
down_revision = '4ec1d1bb1742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thought', schema=None) as batch_op:
        batch_op.add_column(sa.Column('space', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('tombstone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.JSON(), nullable=True))
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thought', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('likes')
        batch_op.drop_column('tombstone')
        batch_op.drop_column('space')

    # ### end Alembic commands ###
