"""empty message

Revision ID: f49c060cc33f
Revises: 8562243d20d9
Create Date: 2025-05-15 15:43:34.215587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49c060cc33f'
down_revision = '8562243d20d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thought', schema=None) as batch_op:
        batch_op.alter_column('emotions',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thought', schema=None) as batch_op:
        batch_op.alter_column('emotions',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
